name: Create New Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Dependencies
        run: |
          brew install create-dmg

      - name: Certificates
        uses: apple-actions/import-codesign-certs@v5
        with:
          p12-file-base64: ${{ secrets.DEV_ID_P12_BASE64 }}
          p12-password: ${{ secrets.DEV_ID_P12_PASSWORD }}

      - name: Xcode 16.4
        run: |
          sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer

      - name: Build
        run: |
          make

      - name: Codesign & Notarize
        run: |
          codesign --deep --force --options runtime --sign "${{ secrets.DEV_ID_IDENTITY_NAME }}" packages/EasyPKG.app
          ln -s /Applications packages/Applications
          create-dmg EasyPKG.dmg packages
          xcrun notarytool submit EasyPKG.dmg --apple-id "${{ secrets.APPLE_ID_EMAIL }}" --password "${{ secrets.APPLE_ID_PASSWORD }}" --team-id "${{ secrets.APPLE_ID_TEAM }}" --wait
          xcrun stapler staple EasyPKG.dmg

      - name: Setup Sparkle
        id: get_version
        run: |
          curl -L -o Sparkle-2.4.2.tar.xz https://github.com/sparkle-project/Sparkle/releases/download/2.8.0/Sparkle-2.8.0.tar.xz
          tar -xJf Sparkle-2.4.2.tar.xz
          mkdir update
          mv EasyPKG.dmg update/
          chmod +x ./bin/generate_appcast
                    
          VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" packages/*.app/Contents/Info.plist)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Make Appcast
        run: |
          echo "$SPARKLE_PRIVATE_KEY" | ./bin/generate_appcast --ed-key-file - --download-url-prefix https://github.com/khcrysalis/EasyPKG/releases/latest/download/ update/
        env:
          SPARKLE_PRIVATE_KEY: ${{ secrets.SPARKLE_PRIVATE_KEY }}

      - name: Draft
        uses: softprops/action-gh-release@v2
        with:
          name: EasyPKG v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          files: |
            update/EasyPKG.dmg
            update/appcast.xml
          body: |
            > [!WARNING]
            > Some of the actions in this app can also be considered dangerous, only delete whats necessary, and not entire drives, you've been warned.
            
            ## What's Changed
          generate_release_notes: false
          fail_on_unmatched_files: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
